apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: devbox
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: devbox
    app.kubernetes.io/managed-by: kustomize
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - command:
        - /manager
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8443
        - --default-base-image=docker.io/library/alpine:3.23
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/labring/sealos-devbox-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          privileged: true
          runAsUser: 0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 640Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/containerd
          name: containerd-run-dir
        - mountPath: /var/run/containerd
          name: containerd-var-run-dir
        - mountPath: /var/lib/containerd
          mountPropagation: Bidirectional
          name: containerd-dir
        - mountPath: /var/lib/containerd-stargz-grpc
          mountPropagation: Bidirectional
          name: stargz-dir
        - mountPath: /etc/containerd/certs.d
          name: hosts-dir
        - mountPath: /tmp
          name: tmp-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        devbox.sealos.io/node: ""
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: controller-manager
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: devbox.sealos.io/node
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      volumes:
      - hostPath:
          path: /run/containerd
          type: Directory
        name: containerd-run-dir
      - hostPath:
          path: /var/run/containerd
          type: Directory
        name: containerd-var-run-dir
      - hostPath:
          path: /var/lib/containerd
          type: Directory
        name: containerd-dir
      - hostPath:
          path: /var/lib/containerd-stargz-grpc
          type: DirectoryOrCreate
        name: stargz-dir
      - hostPath:
          path: /etc/containerd/certs.d
          type: Directory
        name: hosts-dir
      - hostPath:
          path: /tmp
          type: Directory
        name: tmp-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
